name: Deploy to EC2

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -t your-image-name . # Dockerfileがあるディレクトリで実行

      - name: Save Docker image
        run: docker save your-image-name > image.tar

      - name: Deploy to EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu # EC2のユーザー名に合わせて変更
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          files: image.tar
          target: /tmp

      - name: SSH to EC2 and deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu # EC2のユーザー名に合わせて変更
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            docker load -i /tmp/image.tar
            docker stop your-container-name || true
            docker rm your-container-name || true
            docker run -d -p 80:5000 --name your-container-name your-image-name
            rm /tmp/image.tar # 一時ファイルを削除
