name: CI/CD Pipeline

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@master

      - name: SSH to EC2 and Deploy
        uses: appleboy/ssh-action@master # v2が解決しない問題への一時的な対応
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            cd /home/ubuntu # ルートディレクトリを指定
            docker-compose down # 古いコンテナを停止
            docker-compose build --no-cache # イメージをビルド（変更があった場合のみ）
            docker-compose up -d # コンテナを起動

      - name: Health Check
        run: |
          curl --fail --retry 10 --retry-delay 10 http://52.68.119.64:5001/view_calendar

      - name: Deployment Complete
        run: echo "Deployment to EC2 complete!"
