name: Deploy to EC2

on:
  push:
    branches:
      - feature/new-directory-type

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15 # バージョンをdocker-composeに合わせました
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: test_password
          POSTGRES_DB: test_db
        ports:
          - 5432:5432
        volumes: # init.sqlのマウント
          - ./init.sql:/docker-entrypoint-initdb.d/init.sql # docker-composeと同様のマウント
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install psycopg2-binary
      - name: Run tests
        env:
          TEST_DATABASE_URL: postgresql://postgres:test_password@localhost:5432/test_db
        run: |
          pytest
