name: Deploy to EC2

on:
  push:
    branches:
      - feature/new-directory-type

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Docker
        uses: docker/setup-docker@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Start Docker Compose
        run: |
          docker compose -f docker-compose.dev.yml up -d
      - name: Wait for PostgreSQL
        run: |
          sleep 10
          docker exec $(docker ps -q --filter ancestor=postgres:15) pg_isready -U postgres
      - name: Run tests
        env:
          TEST_DATABASE_URL: postgresql://postgres:test_password@localhost:5432/test_db
        run: |
          pytest
      - name: Stop Docker Compose
        if: always()
        run: |
          docker compose -f docker-compose.dev.yml down
