name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Check for changes
        id: check_changes
        run: |
          if [[ $(git diff --name-only HEAD^ HEAD) ]]; then
            echo "::set-output name=has_changes::true"
          else
            echo "::set-output name=has_changes::false"
          fi

      - name: Deploy to EC2 (using SSH)
        if: steps.check_changes.outputs.has_changes == 'true'
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_PUBLIC_IP }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/ubuntu/event_manager_v5
            git pull origin main
            docker compose up --build -d
      - name: No changes to deploy
        if: steps.check_changes.outputs.has_changes == 'false'
        run: echo "No changes to deploy. Skipping deployment."
